const Map<String, String> viVN = {
  'license_no': "Giay phep lai xe",
  'confirm or change': "Xác nhận hoặc thay đổi điểm đón",
  'confirmed_pickup' : "Điểm đón đã được xác nhận",
  'choose vehicle':"Chọn xe",
  'distance':"Khoảng cách",
  'duration':"Thời gian",
  'select a vehicle' : "Vui lòng chọn một loại xe",
  'payment info':"Thông tin thanh toán",
  'add stopover':"Thêm điểm dừng",
  'payment method':"Phương thức thanh toán",
  'wallet': "Ví",
  'Select_service': "Chọn dịch vụ",
  'Let’s choose the transport service suitable for you': "Lựa chọn loại dịch vụ phù hợp với bạn",
  'from':"Điểm đón",
  'to':"Điểm đích",
  'booking':"Đặt xe",
  'airport':"Xe sân bay",
  'longtrip': "Xe đường dài",
  'version':"Phiên bản",
  'account':"Tài khoản",
  'notification':"Thông báo",
  'activities':"Hoạt động",
  'please_wait':"Đợi chút...",
  'no':"No",
  'yes':"Đồng ý",
  'delete_account':"Xóa tài khoản",
  'Are_you_sure_you_want_to_delete_account?':"Bạn có chắc chắn muốn xóa tài khoản ?",
  'help_via_phone':"Hỗ trợ qua điện thọại",
  'help_via_email':"Hỗ trợ qua email",
  'welcome': "Xin chào",
  'chang_language':"Ngôn ngữ",
  'intro':"Giới thiệu",
  'support':"Hỗ trợ",
  'share':"Chia sẻ",
  'chang_password': "Đổi mật khẩu",
  'are_want_to_logout':"Bạn thật sự muốn đăng xuất",
  'log_out': "Đăng xuất",
  'forgot_password': "Quên mật khẩu",
  'Don’t have an account yet?': "Chưa có tài khoản?",
  'Already have an account?': "Đã có tài khoản ?",
  'sign_up': "Đăng ký",
  'login_with_phone_number' : "Đăng nhập bằng số điện thoại",
  'login_with_email' : "Đăng nhập bằng Email",
  'app_name': "Taxi Sân bay",
  'intro_title_one': "Chọn Vị Trí Của Bạn",
  'intro_title_two': "Yêu Cầu Đi Xe",
  'into_dec_one':
  "Hành khách có thể chọn vị trí mong muốn của họ và biết thời gian để đến đích và số tiền họ cần phải trả.",
  'into_dec_two':
  "Hành khách có thể yêu cầu đi xe dễ dàng từ bất cứ đâu, bất cứ lúc nào với vài bước đơn giản.",
  'select_language': "Chọn ngôn ngữ của bạn",
  'next': "Tiếp theo",
  'done': "Hoàn thành",
  'skip': "Bỏ qua",
  'enter_information': "Nhập \nthông tin của bạn",
  'phone': "Số điện thoại",
  'password': "Mật khẩu",
  'required': "*bắt buộc",
  'forgot': "Quên mật khẩu?",
  'login': "Đăng nhập",
  'create': "Tạo tài khoản khách hàng",
  'full_name': "Họ và Tên",
  'email': "Email",
  'address': "Địa chỉ",
  'confirm_password': "Xác nhận mật khẩu",
  'send': "Gửi",
  'already_register': "Đã đăng ký, kết nối",
  'home': "Trang chủ",
  'favorite_ride': "Chuyến đi yêu thích",
  'new_ride': "Mới",
  'confirmed': "Đã xác nhận",
  'on_ride': "Đang đi",
  'completed': "Đã hoàn thành",
  'canceled': "Hủy",
  'rent_a_vehicle': "Thuê xe",
  'rented_vehicle': "Xe đã thuê",
  'promo_code': "Mã khuyến mãi",
  'change_language': "Thay đổi ngôn ngữ",
  'sign_out': "Đăng xuất",
  'contact_us': "Liên hệ chúng tôi",
  'rate_business': "Đánh giá doanh nghiệp",
  'my_profile': "Hồ sơ của tôi",
  'delete': "Xóa",
  'new': "Mới",
  'view_path': "Xem đường đi",
  'call': "Gọi",
  'driver_name': "Tên tài xế",
  'conform_your_ride': "Xác nhận chuyến đi của bạn",
  'safe_message': "Tôi cảm thấy không an toàn",
  'sos': "SOS",
  'add_review': "Thêm đánh giá",
  'add_complaint': "Thêm khiếu nại",
  'rejected': "Đã bị từ chối",
  'book_now': "ĐẶT NGAY",
  'cancel': "Hủy",
  'submit': "Gửi",
  'title': "Tiêu đề",
  'message': "Tin nhắn",
  'submit_query_message': "Gửi yêu cầu của bạn",
  'term_policy': "Điều khoản & Chính sách",
};
