const Map<String, String> viVN = {
  'continue': "Tiếp tục",
  'airport_private': "Xe riêng sân bay",
  'details':" Chi tiêt",
  'history': "Lịch sử",
  'Trip rejected': "Chuyến đi đã bị từ chối",
  'name' : "Tên",
  'estimated': "Ước tính",
  'trip detail': "Chi tiết chuyến đi ",
  'completed': "Hoàn thành",
  'Failed to load terms of service': "Không thể tải điều khoản dịch vụ",
  'Failed to load wallet data': "Không thể tải dữ liệu ví",
  'Failed to load vehicle data': "Không thể tải dữ liệu xe",
  'Login failed. Please try again.': "Đăng nhập không thành công. Vui lòng thử lại.",
  'Request timed out. Please try again.': "Yêu cầu đã hết thời gian. Vui lòng thử lại.",
  'No internet connection. Please check your network.': "Không có kết nối internet. Vui lòng kiểm tra mạng của bạn.",
  'Location permissions are permanently denied, we cannot request permissions.': "Quyền truy cập vị trí bị từ chối vĩnh viễn, chúng tôi không thể yêu cầu cấp quyền.",
  'Location permissions are denied': "Quyền truy cập vị trí bị từ chối",
  'Location services are disabled.': "Dịch vụ vị trí đã bị tắt.",
  'Failed to load album': "Không thể tải album",
  'Something want wrong. Please try again later': "Đã xảy ra sự cố. Vui lòng thử lại sau.",
  'Press Back button again to Exit': "Nhấn nút Quay lại một lần nữa để thoát",
  'no vehicle data': "Không có dữ liệu xe",
  'help via phone': "Hỗ trợ qua điện thoại",
  'notification detail': "Chi tiết thông báo",
  'no information wallet': "Không có thông tin ví",
  'please enter name': "Vui lòng nhập tên",
  'account delete': "Xóa tài khoản",
  'change information': "Thay đổi thông tin",
  'change password': "Thay đổi mật khẩu",
  'current password': "Mật khẩu hiện tại",
  'confirm password': "Xác nhận mật khẩu",
  "password field do not match !!": "Mật khẩu không khớp!!",
  'password change successfully': "Thay đổi mật khẩu thành công",
  '*required': "*bắt buộc",
  "new password": "Mật khẩu mới",
  'select vehicle type': "Chọn loại xe",
  'license_no': "Số GPLX",
  'email not valid': "Email không hợp lệ",
  'full name': "Họ và tên",
  'Please Enter OTP': "Vui lòng nhập mã OTP",
  'Password change successfully!': "Thay đổi mật khẩu thành công!",
  'Confirm password is invalid': "Xác nhận mật khẩu không hợp lệ",
  'Password required at least 6 characters': "Mật khẩu yêu cầu ít nhất 6 ký tự",
  'please try again later': "Vui lòng thử lại sau",
  'email': "Email",
  'Enter the email address we will send an OTP to create new password.': "Nhập địa chỉ email, chúng tôi sẽ gửi mã OTP để tạo mật khẩu mới.",
  "signup phone": "Đăng ký qua điện thoại",
  'login phone': "Đăng nhập qua điện thoại",
  'sending OTP': "Đang gửi mã OTP",
  'start': "Bắt đầu",
  'cash': "Tiền mặt",
  'wallet': "Ví",
  'airport_sharing': 'Xe ghép sân bay',
  'you_have_new_trip': 'Bạn có chuyến đi mới',
  'no_information_wallet': 'Không có thông tin ví',
  'no_vehicle_data': 'Không có dữ liệu xe',
  'vehicle_type': "Loại xe",
  'brand': "Hãng xe",
  'model': "Mẫu xe",
  'license_plate': "Biển số xe",
  'vehicle_info' : "Thông tin phương tiện",
  'confirm': "Xác nhận",
  'confirmed pickup' : "Xác nhận điểm đón",
  'choose vehicle':"Chọn xe",
  'distance':"Khoảng cách",
  'duration':"Thời gian",
  'select a vehicle' : "Vui lòng chọn một loại xe",
  'payment info':"Thông tin thanh toán",
  'add stopover':"Thêm điểm dừng",
  'payment method':"Phương thức thanh toán",
  'Select_service': "Chọn dịch vụ",
  'Let’s choose the transport service suitable for you': "Lựa chọn loại dịch vụ phù hợp với bạn",
  'from':"Điểm đón",
  'to':"Điểm đích",
  'booking':"Đặt xe",
  'longtrip': "Xe đường dài",
  'version':"Phiên bản",
  'account':"Tài khoản",
  'notification':"Thông báo",
  'activities':"Hoạt động",
  'please_wait':"Đợi chút...",
  'no':"No",
  'yes':"Đồng ý",
  'delete_account':"Xóa tài khoản",
  'Are_you_sure_you_want_to_delete_account?':"Bạn có chắc chắn muốn xóa tài khoản ?",
  'help_via_phone':"Hỗ trợ qua điện thọại",
  'help_via_email':"Hỗ trợ qua email",
  'welcome': "Xin chào",
  'chang_language':"Ngôn ngữ",
  'intro':"Giới thiệu",
  'support':"Hỗ trợ",
  'share':"Chia sẻ",
  'chang_password': "Đổi mật khẩu",
  'are_want_to_logout':"Bạn thật sự muốn đăng xuất",
  'log_out': "Đăng xuất",
  'forgot_password': "Quên mật khẩu",
  'Don’t have an account yet?': "Chưa có tài khoản?",
  'Already have an account?': "Đã có tài khoản ?",
  'sign_up': "Đăng ký",
  'login_with_phone_number' : "Đăng nhập bằng số điện thoại",
  'login_with_email' : "Đăng nhập bằng Email",
  'app_name': "Taxi Sân bay",
  'intro_title_one': "Chọn Vị Trí Của Bạn",
  'intro_title_two': "Yêu Cầu Đi Xe",
  'into_dec_one':
  "Hành khách có thể chọn vị trí mong muốn của họ và biết thời gian để đến đích và số tiền họ cần phải trả.",
  'into_dec_two':
  "Hành khách có thể yêu cầu đi xe dễ dàng từ bất cứ đâu, bất cứ lúc nào với vài bước đơn giản.",
  'select_language': "Chọn ngôn ngữ của bạn",
  'next': "Tiếp theo",
  'done': "Hoàn thành",
  'skip': "Bỏ qua",
  'enter_information': "Nhập \nthông tin của bạn",
  'phone': "Số điện thoại",
  'password': "Mật khẩu",
  'required': "*bắt buộc",
  'forgot': "Quên mật khẩu?",
  'login': "Đăng nhập",
  'create': "Tạo tài khoản khách hàng",
  'full_name': "Họ và Tên",
  'address': "Địa chỉ",
  'confirm_password': "Xác nhận mật khẩu",
  'send': "Gửi",
  'already_register': "Đã đăng ký, kết nối",
  'home': "Trang chủ",
  'favorite_ride': "Chuyến đi yêu thích",
  'new_ride': "Mới",
  'confirmed': "Đã xác nhận",
  'on_ride': "Đang đi",
  'canceled': "Hủy",
  'rent_a_vehicle': "Thuê xe",
  'rented_vehicle': "Xe đã thuê",
  'promo_code': "Mã khuyến mãi",
  'change_language': "Thay đổi ngôn ngữ",
  'sign_out': "Đăng xuất",
  'contact_us': "Liên hệ chúng tôi",
  'rate_business': "Đánh giá doanh nghiệp",
  'my_profile': "Hồ sơ của tôi",
  'delete': "Xóa",
  'new': "Mới",
  'view_path': "Xem đường đi",
  'call': "Gọi",
  'driver_name': "Tên tài xế",
  'conform_your_ride': "Xác nhận chuyến đi của bạn",
  'safe_message': "Tôi cảm thấy không an toàn",
  'sos': "SOS",
  'add_review': "Thêm đánh giá",
  'add_complaint': "Thêm khiếu nại",
  'rejected': "Đã bị từ chối",
  'book_now': "ĐẶT NGAY",
  'cancel': "Hủy",
  'submit': "Gửi",
  'title': "Tiêu đề",
  'message': "Tin nhắn",
  'submit_query_message': "Gửi yêu cầu của bạn",
  'term_policy': "Điều khoản & Chính sách",
};
