name: driverapp
description: ""
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:

  dio: ^5.4.0
  dartz: ^0.10.0

  # Quản lý trạng thái và điều hướng
  get: ^4.6.6

  pinput: ^5.0.0
  pusher_channels_flutter: ^2.2.1
  geolocator: ^13.0.1

  # Giao diện người dùng và widget
  flutter_easyloading: ^3.0.5 # Hiển thị trạng thái tải
  line_awesome_flutter: ^3.0.1 # Biểu tượng
  flutter_svg: ^2.0.10+1 # Hiển thị SVG
  flutter_polyline_points: ^2.1.0 # Vẽ đường trên bản đồ
  time_picker_spinner_pop_up: ^2.0.0 # Chọn thời gian

  # Xử lý văn bản và nhập liệu
  intl: ^0.19.0 # Hỗ trợ đa ngôn ngữ
  flutter_html: ^3.0.0-alpha.5 # Hiển thị HTML
  html: ^0.15.4 # Xử lý HTML
  pin_code_fields: ^8.0.1 # Trường nhập mã PIN
  intl_phone_number_input: ^0.7.4 # Nhập số điện thoại quốc tế
  uuid: ^4.4.2 # Tạo UUID

  # Lưu trữ và chia sẻ dữ liệu
  shared_preferences: ^2.2.3 # Lưu trữ dữ liệu đơn giản

  # Định vị và bản đồ
  location:  ^6.0.2 # Truy cập dịch vụ định vị
  vietmap_flutter_gl: ^2.2.1
  vietmap_flutter_plugin: ^0.3.0
  flutter_typeahead: ^4.8.0

  # Khởi động URL và liên kết
  url_launcher: ^6.3.0 # Khởi động URL

  flutter_datetime_picker_plus: ^2.2.0

  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependencies_override:
  dio: ^5.4.0
  dartz: 0.9.10

flutter:

  assets:
    - assets/svg/
    - assets/images/
    - assets/icons/
    - assets/file/
    - assets/flags/
    - assets/

  uses-material-design: true

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 700

